### PR TITLE
Fmd fixes

### PR DESCRIPTION
**Pull request by ford-prefect**
I'm not sure about the relative references, but the other stuff should be straight-forward enough.

### CODE REVIEW

**Comment by ford-prefect** [comment]
I've verified that the very first commit in this series (`5c14ea9fdb6ee25e7bf65176ee0e5ce6184dc306`) fixes loading with redocly.

**Comment by beckn-dev** [comment]
I'm getting errors in the Swaggerhub online editor. I think you need to specify a basePath before adding relative references.

**Comment by beckn-dev** [comment]
Can you do a Re-PR with the other fixes ?

**Comment by ford-prefect** [comment]
@beckn-dev done now

**Pull request merged**
