### PR TITLE
Issue Fixes

### PR DESCRIPTION
**Pull request by emmayank**

### CODE REVIEW

**Comment by emmayank** [comment]
Issue Resolved :
1. #377 
2. #376 
3. #375 
4. #355 
5. #354 
6. #350

**Comment by emmayank** [comment]
7. #348

**Comment by emmayank** [comment]
**Other Issue Fixes**
1. Support & on_support Schema updated
2. Price Value replaced by string
3. Xinput Schema Updated
4. Payment Object schema updated

**Comment by emmayank** [comment]
8. #343

**Comment by ravi-prakash-v** [comment]
Hi @emmayank, please raise the PR to draft. Thanks

**Comment by emmayank** [comment]
Hi @ravi-prakash-v 

1. I have raised the PR to `draft `branch now.
2. After making all changes to the schema, i have generated the API specs 1.2 version using the `swagger-cli` command.

Please review & let me know if this is ready to be merged

Thanks
emmayank

**Review by ravi-prakash-v — APPROVED** [review]

**Comment by ravi-prakash-v** [comment]
@emmayank I have approved these changes. You can go ahead and merge them.

**Comment by emmayank** [comment]
@ravi-prakash-v , Ok Merging them now and closing the respective issues.

**Pull request merged**
