### PR TITLE
Updating Customer and Support schema to add new properties

### PR DESCRIPTION
**Pull request by shenoyninad**
Changes include
- Updating Customer schema to include an ID property that will be used to identify a customer
- Updating Customer schema to include the organization property that is a reference to the Organization schema.
- Updating the Support schema to modify the `ref_id` property to `order_id`

### CODE REVIEW

**Comment by shenoyninad** [comment]
Hi @ravi-prakash-v, I created a new PR. This has all the changes we discussed. Can you please take a look at it and approve it if everything looks good?

**Review by venkatramanm — COMMENTED** [review]
Seems like the Customer schema and  Agent schema are the same except for being rateable and having a Rating. May be customer should also be rateable. I suggest we derive Customer from Agent.. FulfillmentAgent from Agent, Possibly fulfillment.agent could be of type FulfillmentAgent. That way we can future proof any deviation. 

That being said, I think we can postpone creation of FulfillmentAgent at a later point too.  @ravi-prakash-v @shenoyninad

**Review by ravi-prakash-v — CHANGES_REQUESTED** [review]
Please do not update the transaction.yaml file. Please update the schema file in the schemas folder and rebuild the transaction.yaml

**Comment by ravi-prakash-v** [comment]
@shenoyninad @venkatramanm can we create a discussion around the use case, arrive at an agreed upon schema, then raise an Issue (label: enhancement) linked to the discussion, then create a PR linked to that issue? Let us not have spec discussions on PRs. Or else PRs remain open for a long time.

**Comment by venkatramanm** [comment]
Makes sense

**Review by ravi-prakash-v — APPROVED** [review]

**Pull request merged**
