### PR TITLE
Added fulfillment_id in Item schema object

### PR DESCRIPTION
**Pull request by techframewirk**

### CODE REVIEW

**Review by beckn-dev — APPROVED** [review]

**Comment by beckn-dev** [comment]
Approved by @beckn-dev.

@pkapustin kindly review.

**Comment by pkapustin** [comment]
Should this field be mandatory?

**Comment by core-wg-admin** [comment]
Not required.

**Comment by pkapustin** [comment]
@core-wg-admin Do you mean that it should be part of the network policy whether to refer to a fulfillment id in the items or not?

**Pull request merged**
